// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"github.com/green-finger/microservices/plants/interface/controller"
	"github.com/green-finger/microservices/plants/interface/presenter"
	"github.com/green-finger/microservices/plants/usecase/plants"
)

// Injectors from wire.go:

func InitPlant() *controller.PlantController {
	plantsPresenter := presenter.NewPlantPresenter()
	plantsInteractor := usecase.NewPlantInteractor(plantsPresenter)
	plantsController := controller.NewPlantController(plantsInteractor)
	return plantsController
}
