// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"github.com/green-finger/microservices/bff/interface/controller"
	"github.com/green-finger/microservices/bff/interface/presenter"
	"github.com/green-finger/microservices/bff/usecase/plant"
)

// Injectors from wire.go:

func InitPlant() *controller.PlantController {
	plantPresenter := presenter.NewPlantPresenter()
	plantInteractor := usecase.NewPlantInteractor(plantPresenter)
	plantController := controller.NewPlantController(plantInteractor)
	return plantController
}
